# Generated by Django 2.2 on 2019-05-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190516_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='login.User1', verbose_name='资产所有者'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user0', to='login.User1', verbose_name='资产所有者'),
        ),
    ]
